/** Business type options for shop owner register / profile (`shop_owners.business_type`). */
export const SHOP_BUSINESS_TYPES = [
  'Hair, beauty & cosmetics',
  'Electronics',
  'Liquor',
  'Pharmacy',
  'Farm Produce',
  'Tools & Car parts',
  'Office and stationery',
  'Restaurants',
  'Fashion',
  'Clothing',
  'Grocery & Supermarkets',
  'Restaurants & Takeaways',
  'Bakeries',
  'Butcheries',
  'Pharmacies',
  'Health & Beauty',
  'Clothing & Fashion',
  'Shoes & Accessories',
  'Phones & Electronics',
  'Home & Furniture',
  'Hardware & Building',
  'Baby & Kids',
  'Books & Stationery',
  'Liquor & Beverages',
];
